name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: setup snapcraft
      run: sudo snap install snapcraft --classic
    - run: yarn install --frozen-lockfile
    - name: setup dummy app node deps
      run: cd test/fixtures/app && yarn install --frozen-lockfile
    - run: yarn test_with_coverage
      env:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.lcov
        env_vars: NODE_VERSION
      env:
        NODE_VERSION: ${{ matrix.node-version }}
